# Generated by Django 5.1.4 on 2024-12-24 04:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('predefined_category', models.CharField(blank=True, choices=[('job', 'Job'), ('investment', 'Investment'), ('freelance', 'Freelance')], max_length=200)),
                ('is_shared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recurring', 'RECURRING'), ('one-time', 'ONE-TIME')], default=('recurring', 'RECURRING'), max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateField(blank=True, default=datetime.datetime(2025, 1, 23, 4, 57, 12, 200009, tzinfo=datetime.timezone.utc), null=True)),
                ('currency', models.CharField(choices=[('toman', 'TOMAN'), ('dollar', 'USD')], default=('toman', 'TOMAN'), max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='core.incomecategory')),
            ],
        ),
    ]
