# Generated by Django 5.1.4 on 2024-12-25 01:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 24, 1, 33, 14, 565331, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.incomecategory'),
        ),
    ]
