# Generated by Django 5.1.4 on 2024-12-25 02:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_income_end_at_alter_income_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedIncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('job', 'Job'), ('investment', 'Investment'), ('freelance', 'Freelance')], max_length=200, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('category', 'user')},
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('toman', 'TOMAN'), ('dollar', 'USD')], db_index=True, default=('toman', 'TOMAN'), max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime(2025, 1, 24, 2, 23, 51, 610716, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('recurring', 'RECURRING'), ('one-time', 'ONE-TIME')], db_index=True, default=('recurring', 'RECURRING'), max_length=200),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='predefined_category',
        ),
    ]
