# Generated by Django 5.1.4 on 2024-12-25 03:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_incomecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime(2025, 1, 24, 3, 18, 59, 60468, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='predefined_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.predefinedincomecategory', unique=True),
        ),
    ]
