# Generated by Django 5.1.4 on 2024-12-25 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_income_end_at_alter_incomecategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecategory',
            name='is_shared',
        ),
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime(2025, 1, 24, 3, 47, 57, 404063, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
