# Generated by Django 5.1.4 on 2024-12-25 03:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_incomecategory_is_shared_alter_income_end_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 24, 3, 57, 22, 840246, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('recurring', 'RECURRING'), ('one-time', 'ONE-TIME')], default=('recurring', 'RECURRING'), max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('user', 'source')},
        ),
    ]
