# Generated by Django 5.1.4 on 2024-12-25 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_income_end_at_alter_income_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 24, 4, 1, 3, 21457, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
