# Generated by Django 5.1.4 on 2024-12-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_income_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
