# Generated by Django 5.1.4 on 2024-12-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_incomecategory_predefined_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecategory',
            name='predefined_category',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='PredefinedIncomeCategory',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
