# Generated by Django 5.1.4 on 2024-12-27 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_remove_incomecategory_predefined_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(blank=True, choices=[('investmnet', 'INVESTMENT'), ('freelance', 'FREELANCE'), ('job', 'JOB')], max_length=200, unique=True)),
                ('expense', models.CharField(blank=True, choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('insurance', 'Insurance'), ('entertainment', 'Entertainment'), ('health_medical', 'Health & Medical'), ('education', 'Education'), ('debt_repayment', 'Debt Repayment'), ('savings_investments', 'Savings & Investments'), ('clothing', 'Clothing'), ('personal_care', 'Personal Care'), ('childcare', 'Childcare'), ('charity_donations', 'Charity & Donations'), ('subscriptions', 'Subscriptions'), ('business_expenses', 'Business Expenses'), ('taxes', 'Taxes'), ('gifts_donations', 'Gifts & Donations'), ('travel', 'Travel')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('predefined_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.predefinedtransactioncategory')),
                ('user', models.ManyToManyField(related_name='income_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'INCOME'), ('expense', 'EXPENSE')], default=('income', 'INCOME'), max_length=200)),
                ('period_type', models.CharField(choices=[('recurring', 'RECURRING'), ('one-time', 'ONE-TIME')], default=('recurring', 'RECURRING'), max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('toman', 'TOMAN'), ('dollar', 'USD')], db_index=True, default=('toman', 'TOMAN'), max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.transactioncategory')),
            ],
            options={
                'unique_together': {('user', 'source')},
            },
        ),
    ]
