# Generated by Django 5.1.4 on 2024-12-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_expense_predefinedtransactioncategory_expense_default_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefinedtransactioncategory',
            old_name='expense_default_choices',
            new_name='expense_category',
        ),
        migrations.RenameField(
            model_name='predefinedtransactioncategory',
            old_name='income_default_choices',
            new_name='income_category',
        ),
    ]
