# Generated by Django 5.1.4 on 2024-12-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_expense_default_choices_predefinedtransactioncategory_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedtransactioncategory',
            name='income_category',
            field=models.CharField(blank=True, choices=[('investmnet', 'Inventory='), ('freelance', 'Freelance'), ('job', 'Job')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('toman', 'Toman'), ('dollar', 'USD')], db_index=True, default=('toman', 'Toman'), max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='period_type',
            field=models.CharField(choices=[('recurring', 'Recurring'), ('one-time', 'one-time')], default=('recurring', 'Recurring'), max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default=('income', 'Income'), max_length=200),
        ),
    ]
