# Generated by Django 5.1.4 on 2024-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_predefinedtransactioncategory_income_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedtransactioncategory',
            name='income_category',
            field=models.CharField(blank=True, choices=[('investmnet', 'Inventory'), ('freelance', 'Freelance'), ('job', 'Job')], max_length=200, unique=True),
        ),
    ]
