# Generated by Django 5.1.4 on 2024-12-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_predefinedtransactioncategory_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedtransactioncategory',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=200),
        ),
    ]
