# Generated by Django 5.1.4 on 2024-12-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_predefinedtransactioncategory_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedtransactioncategory',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=200),
        ),
    ]
