# Generated by Django 5.1.4 on 2024-12-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_predefinedtransactioncategory_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
