# Generated by Django 5.1.4 on 2024-12-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transactioncategory_is_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncategory',
            old_name='user',
            new_name='users',
        ),
    ]
