# Generated by Django 5.1.4 on 2024-12-28 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_transaction_type_predefinedtransactioncategory_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='predefined_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.predefinedtransactioncategory'),
        ),
    ]
